language: node_js
node_js: "v10.16.0"

cache: npm

script:
- npm audit
- npm run build
- npm run deploy:ci

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/" # matches branch names using semantic versioning (e.g. "v0.0.1")
  - "master"